FROM digitalasset/daml-sdk:0.12.15-master

WORKDIR /home/sdk

COPY ui-backend.conf frontend-config.js /home/sdk/

EXPOSE 7500

CMD da run navigator -- server ${SANDBOX_HOST} ${SANDBOX_PORT} --port 7500 --config-file ui-backend.conf
