#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

ARG sdk_vsn=1.0.1

FROM digitalasset/daml-sdk:${sdk_vsn}

WORKDIR /home/daml

COPY target/structured-products.dar \
  scripts/wait_for_ledger.sh \
  scripts/run_daml_script.sh \
  /home/daml/

USER root
RUN chown daml structured-products.dar
USER daml

EXPOSE 6865

CMD ./run_daml_script.sh localhost 6865 structured-products.dar DA.RefApps.StructuredProducts.MarketSetup:marketSetupScript & \
  ~/.daml/bin/daml sandbox --address 0.0.0.0 --port 6865 structured-products.dar
