#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: '2.1'
services:
  structured-products-sandbox:
    image: digitalasset/structured-products-sandbox:1.0.0
    build:
      context: .
      dockerfile: Dockerfile-sandbox
    ports:
      - "127.0.0.1:6865:6865"
      - "127.0.0.1:7500:7500"
  structured-products-bots:
    image: digitalasset/structured-products-bots:1.0.0
    build:
      context: .
      dockerfile: Dockerfile-bots
    depends_on:
      - "structured-products-sandbox"
    environment:
      - SANDBOX_HOST=structured-products-sandbox
      - SANDBOX_PORT=6865
      # - BOT_TOKEN=${BOT_TOKEN:?provide BOT_TOKEN environment variable}
      # - CHAT_ID=${CHAT_ID:?provide CHAT_ID environment variable}
